server:
  port: 8011

spring:
  application:
    name: cloud-porducta
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka1:8001/eureka,http://eureka2:8002/eureka
